---
title: "Code review for manuscript"
author: "Jeff Hollister"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Table 1

- 3_ard_model/water_temp.R for Landsat(LakeCloudFree)
  - rf model in 3_ard_model/ard_model.rda
  - numbers match!
- 3_ard_model/water_temp_no_clouds.R for Landsat(SceneCloudFree)
  - rf model in 3_ard_model/ard_no_clouds_model.rda
  - numbers match!
- 4_insitu_model/water_temp_insitu.R for in situ
  - rf model in 4_insitu_model.rda
  - numbers not quite right...  Re-running model.
  - Still same, looks like some slightly off rounding.
  - Corrected in manuscript: jwh, 2024-06-10

## Figure 2

- Code: 2_ard_vs_insitu/insitu_ard_comparison.R
- Figure: atmos_figures/pixel_comparison_w_cloud_cover.jpg

## Figure 3

- Code: lines 186-215 in 5_figure/water_temp_figures.R
- Figure: atmos_figures/figure_2_noclouds.jpg

## Figure 4

- Code: lines 191-245, 281-284 in 5_figures/water_temp_rf_figures_jwh.R
- Figure: local_outputs/fig4_boxplots.jpg
- Need to work on this.  Looks awful with new axis labels

## Figure 5

- Code: lines 387-403 in 5_figure/water_temp_figures.R
- Figure: figure_5alt_noclouds.jpg
- Make sure ARDc and ARDt renamed

## Figure 6

- Code: lines 169-189, 248-266 in 5_figures/water_temp_rf_figures_jwh.R
- Figure: local_outputs/fig_6_var_imp.jpg
- label a, b, c, and have y-axis text match figure 1

## Figure 7

- Code: lines 131-156, 276-279 in 5_figures/water_temp_rf_figures_jwh.R
- Figure: local_output/figure_7_partial_plots.jpg
- Please include (a), (b), ( c), (d)…(h). Please rename ARDt and ARDc. Please make y-axis label match wording in text and Figure 1. Please fix Lat & Long x-axis labels. Please order the figure with a=avg temp; b=30-day; c=day of year; d=longitude; e=latitude; f=area; g=shoreline; and h=elevation to fit the text order.

## Figure 8

- Code: lines 218-258 in 5_figures/water_temp_figures.R
- Figure: atmos_figures/figure_3_noclouds.jpg
- Add stats and n (which stats?)

## Figure 9

- Code: lines 260-323 in 5_figures/water_temp_figures.R
- Figure: atmos_figures/figure_4_noclouds.jpg
- add in a, b, c and re-label ard,

## Old Figure 10

- Code: lines 191-245, 286-289 in 5_figures/water_temp_rf_figures_jwh.R
- Figure: local_output/fig10_nhd_boxplots.jpg
